# exemple de génération de clef

- name: mon premier playbook
  hosts: all
  remote_user: vagrant
  tasks:
  - name: generate SSH key"
    openssh_keypair:
      path: /tmp/pp
      type: rsa
      size: 4096
      state: present
      force: no
    run_once: yes
    delegate_to: localhost
