

# touch avec idempotence

  - name: touch idempotent
    file:
      path: /tmp/pp.txt
      state: touch
      mode: 0755
      modification_time: preserve
      access_time: preserve


# à l'inverse

  - name: dir sans idempotence
    file:
      path: /tmp/pp/1/2/3
      state: touch
      mode: 0755
      modification_time: now
      access_time: now