# version condensée

vars:
  fichiers:
  - { dir: "pp1", file: "fichierA" }
  - { dir: "pp2", file: "fichierB" }
  - { dir: "pp3", file: "fichierC" }
  - { dir: "pp4", file: "fichierD" }
tasks:
- name: création de fichiers
  file:
    path: /tmp/pp/{{ item.dir }}/{{ item.file }}
    state: touch
  with_items:
  - "{{ fichiers }}"
